name: get galileo tle

on:
  schedule:
  - cron: "2 */12 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install dependencies
        run: pip install requests

      - name: Run minute search
        run: |
          python galileo.py > new_galileo.json
          if ! cmp -s new_galileo.json data/galileo.json; then
            mv new_galileo.json data/galileo.json
            git config --global user.name 'GitHub Actions'
            git config --global user.email 'actions@github.com'
            git add data/galileo.json
            git commit -m "Update galileo.json"
            git push
          fi