name: get gps tle

on:
  schedule:
  - cron: "6 */12 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Set up Python
        uses: actions/setup-python@v7
        with:
          python-version: 3.x

      - name: Install dependencies
        run: pip install requests

      - name: Fetch TLEs and commit if changed
        run: |
          python gps.py
          if ! cmp -s new_gps.json data/gps.json; then
            mv new_gps.json data/gps.json
            git config --global user.name 'GitHub Actions'
            git config --global user.email 'actions@github.com'
            git add data/gps.json
            git commit -m "Update gps.json"
            git push
          fi
